### ISSUE TITLE
generate json schema from loopback models

### ISSUE THREAD

**Issue by Traksewt** [backstage/loopback-jsonschema#22]
I can see how to generate the loopback models from json schema using this tool, however it is possible to generate a json schema file from existing loopback models?  I could use a generator like: [json-schema-generator](https://www.npmjs.com/package/json-schema-generator) based on the actual data, but I was hoping to convert the model directly.

**Comment by wpjunior** [comment]
Hi @Traksewt, actually, the focus from this library is to generate loopback models from any json-schema, however we can't implement it now. But what user case are in your mind to implement ?

**Comment by Traksewt** [comment]
We have a production loopback with about ~50 models. We want to now use angular schema form to generate numerous client forms for these models for the next version. We do have extra data specific to loopback in the models, however, auto-generating schema models would be great to speed up dev of the client side forms.

**Comment by Traksewt** [comment]
I created a new project to do this:
[loopback-json-schema-builder](https://www.npmjs.com/package/loopback-json-schema-builder).

Simple conversion at the start, though I'll flesh it out with more as needed.
